import type { Metadata } from "next";
import { ReactNode } from "react";
import "./global.css";
import Navbar from "@/components/navbar/Navbar";

type Props = {
  children: ReactNode;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Props) {
  return (
    <html>
      <body>
        <Navbar />
        <div>{children}</div>
      </body>
    </html>
  );
}
